Repository kowainik/unlift, pull requests merged in 2021-04, with the labels that each got.

#1 Update GitHub Actions config
  .github/workflows/ci.yml
  unlift.cabal
Labels: CI

#3 [#2] Implement MonadUnlift
  src/Unlift.hs
  unlift.cabal
Labels: enhancement

#4 Write README
  README.md
  unlift.cabal
Labels: documentation
